### ISSUE TITLE
possibility of the the web app that you're squatting blocking you?

### ISSUE THREAD

**Issue by Philippeomalley** [cawfree/sameorigin#4]
First of all many thanks for this. It's opened up new alpha for me. However I was wondering if I send an abnormal amount of a certain API call, is there any way that the hosts of the web app catch on to this and alter the webapp to stop this workaround? 

It would be very advantageous for me to be calling an endpoint maybe 20 or 30 times a second. But if that increases the probability of the alpha disappearing then I would rather content myself with something slower that would more resemble a normal user. Thoughts or ideas? Thanks!

**Comment by cawfree** [comment]
Hey, that's good to hear!

I don't think so. Don't get me wrong, websites you use will likely track everything through error monitoring and there will most likely be records of strange requests or failures, but as to whether this would set off any alarms, it really depends on what you're trying to do and who you are trying to do it to.

Excessive API requests are often easily detected because they can cause noticeable system degradation if the backend hasn't been well designed.

You can still definitely spam requests using `sameorigin`, but you'd get more bang for your buck if you can find some way to mask the source, like by [originating your requests through a proxy](https://github.com/cawfree/sameorigin/issues/1) and spreading the workload across multiple independent IPs.

Super happy this is helping you get access to shit you're not normally supposed to - that's the reason this was built!
